server:
  port: 8085

bff:
  catalog:
    base-url: http://localhost:8080
  user:
    base-url: http://localhost:8082
  order:
    base-url: http://localhost:8081
  inventory:
    base-url: http://localhost:8083
