server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hmall
    password: ${DB_PASSWORD:hmall_prod}
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
    hibernate:
      ddl-auto: update
