FROM node:18-alpine AS build-web
WORKDIR /app
COPY frontend/web/package*.json ./
RUN npm ci
COPY frontend/web/ .
RUN npm run build

FROM node:18-alpine AS build-admin
WORKDIR /app
COPY frontend/admin/package*.json ./
RUN npm ci
COPY frontend/admin/ .
RUN npx vite build --base=/admin/

FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY deploy/nginx/default.conf /etc/nginx/conf.d/hmall.conf
COPY --from=build-web /app/dist /usr/share/nginx/html/web
COPY --from=build-admin /app/dist /usr/share/nginx/html/admin
EXPOSE 80
