server:
  port: 8084

payment:
  expire-minutes: 30
  expire-check-interval-ms: 60000
  kafka:
    topic:
      payment-completed: payment.completed
      payment-failed: payment.failed
      payment-expired: payment.expired

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmall
    username: hmall
    password: hmall_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
