server:
  port: 8084

payment:
  expire-minutes: 30
  order-base-url: http://localhost:8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmall
    username: hmall
    password: hmall_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
